rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/wp_0248.jpg"
rm -f "/home/rich/OneDrive/Pictures/google_photos/2003-2016/wp_0248.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/wp_0388.jpg"
rm -f "/home/rich/OneDrive/Pictures/google_photos/2003-2016/wp_0388.jpg"
rm -f "/home/rich/OneDrive/Pictures/google_photos/2019/fish.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/wp_0398.jpg"
rm -f "/home/rich/OneDrive/Pictures/google_photos/2003-2016/wp_0398.jpg"
rm -f "/home/rich/OneDrive/Pictures/google_photos/2019/Snapchat-1717001948.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/wp_0395.jpg"
rm -f "/home/rich/OneDrive/Pictures/google_photos/2003-2016/wp_0395.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/fixing the walk.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/wp_0199.jpg"
rm -f "/home/rich/OneDrive/Pictures/google_photos/2003-2016/wp_0199.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/wp_0257.jpg"
rm -f "/home/rich/OneDrive/Pictures/google_photos/2003-2016/wp_0257.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/20190424_182426.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/20190908_190707.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/IMG_9746.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/4x6/Snapchat-637181840.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/8x10/Mom and Dad 1.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/8x10/pilot.jpg"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/8x10/IMG_9392.jpg"
rm -f "/home/rich/OneDrive/Pictures/Portraits for Mikala/IMG_2331_color.jpg"
rm -f "/home/rich/OneDrive/Pictures/Portraits for Mikala/IMG_2340_color.jpg"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/sep 3 2008-33.jpg"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Pictures/IMG_1375.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Pictures/IMG_1373.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Pictures/IMG_1371.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/_JCPENNEY_JPG_11.gif"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/nathaniel/nathaniel-2.jpg"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Melissa/Melissa  2007 08-09/S6300212.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/2007-09/12-2 -7-31.jpg"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/nathaniel/nathaniel-1.jpg"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/2007-09/12-2 -7-26.jpg"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/hand made/IMG_0340.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/hand made/tray/IMG_0340.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/hand made/tray/IMG_0339.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/hand made/IMG_0341.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/hand made/tray/IMG_0341.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/hand made/165910_280171768780783_940427661_n.jpg"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/RNDVZ2/RNDVZ2-1.avi"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/RNDVZ2/RNDVZ2-2.avi"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/RNDVZ2/RNDVZ2-5.avi"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/RNDVZ2/RNDVZ2-3.avi"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/2012-4-27/IMG_0462.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/2012-4-27/IMG_0463.JPG"
rm -f "/home/rich/OneDrive/Pictures/trick pics/pines.JPG"
rm -f "/home/rich/OneDrive/Pictures/trick pics/pecans 2.JPG"
rm -f "/home/rich/OneDrive/Pictures/2018/142___02/IMG_2384_r1.jpg"
rm -f "/home/rich/OneDrive/Pictures/Old_Photos/Pruitt-Carrick/need catalogged/All Carricks.PSD"
rm -f "/home/rich/OneDrive/Pictures/Old_Photos/Pruitt-Carrick/need catalogged/JohnLogan,Lucinda(Logan)Carrick,,Ruth,MortonCarrick c1916.psd"
rm -f "/home/rich/OneDrive/Pictures/Old_Photos/Pruitt-Carrick/need catalogged/John, Lucinda(Logan), Ruth, Morton c.1916.PSD"
rm -f "/home/rich/OneDrive/Pictures/Old_Photos/Benedict-Williamson/T Coates, K Williamson, L Pyatt, J Gass, M Gass sept 1969.PSD"
rm -f "/home/rich/OneDrive/Pictures/IMG_2848 soft.jpg"
rm -f "/home/rich/OneDrive/Pictures/_35_Archive/2400 hq off.JPG"
rm -f "/home/rich/OneDrive/Pictures/Dad visitation/8x10/IMG_1474.JPG"
rm -f "/home/rich/OneDrive/Pictures/google_photos/2003-2016/IMG_1474.jpg"
rm -f "/home/rich/OneDrive/Pictures/2003/2003-08-02  elephant rock 1 aug 03/IMG_1514.JPG"
rm -f "/home/rich/OneDrive/Pictures/2003/2003 Unsorted/girls_1237.BMP"
rm -f "/home/rich/OneDrive/Pictures/2003/2003-11-22 lockwood baby/prints/IMG_1719.JPG"
rm -f "/home/rich/OneDrive/Pictures/2003/2003-11-22 lockwood baby/prints/IMG_1729.JPG"
rm -f "/home/rich/OneDrive/Pictures/random/marcus_8x10.jpg"
rm -f "/home/rich/OneDrive/Pictures/Portraits for Mikala/Violin and Candle.jpg"
rm -f "/home/rich/OneDrive/Pictures/2004/2004-08-28 camera test/elph_2.JPG"
rm -f "/home/rich/OneDrive/Pictures/2004/2004-08-28 camera test/elph_6.JPG"
rm -f "/home/rich/OneDrive/Pictures/2004/2004-08-28 camera test/elph_3.JPG"
rm -f "/home/rich/OneDrive/Pictures/2004/2004-08-28 camera test/elph_1.JPG"
rm -f "/home/rich/OneDrive/Pictures/2004/2004-08-28 camera test/elph_4.JPG"
rm -f "/home/rich/OneDrive/Pictures/2004/2004-08-28 camera test/elph_5.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/house construction/IMG_2290.JPG"
rm -f "/home/rich/OneDrive/Pictures/Marsha/puppy/unnamed_pup_2096.JPG"
rm -f "/home/rich/OneDrive/Pictures/Marsha/puppy/girls_and_pup_2100_sm.JPG"
rm -f "/home/rich/OneDrive/Pictures/random/Tree of Life, Bahrain.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Other People's pics/Friom Rich/chris and bill.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Other People's pics/Friom Rich/IMG_2230.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Other People's pics/Friom Rich/salala hotel 2.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Other People's pics/Friom Rich/salala hotel.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Other People's pics/Friom Rich/airport.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Other People's pics/Friom Rich/IMG_2149.JPG"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/Other People's pics/Friom Rich/thumrait.JPG"
rm -f "/home/rich/OneDrive/Pictures/random/ferry to Masirah Island.JPG"
rm -f "/home/rich/OneDrive/Pictures/random/Masirah Island.JPG"
rm -f "/home/rich/OneDrive/Pictures/Portraits for Mikala/IMG_0117.JPG"
rm -f "/home/rich/OneDrive/Pictures/Harral Hall/Harral_Hall.jpg"
rm -f "/home/rich/OneDrive/Pictures/Landscapes for big prints/IMG_1199.JPG"
rm -f "/home/rich/OneDrive/Pictures/Landscapes for big prints/IMG_1214 retouched.jpg"
rm -f "/home/rich/OneDrive/Pictures/mom_and_dad_pictures/2016-12-04/021.JPG"
rm -f "/home/rich/OneDrive/Pictures/Camera Roll/2025/08/20250811_181738 1.jpg"
