# This file should contain a list of directories to backup.
# One directory per line
# Directories only, do not use absolute filenames.
# Do not use trailing slashes.
# OK to use spaces in directory paths, no need to surround with quotes.
# All sub directories and files in the specified directories will be backed up to Amazon S3.
# Do not use inline comments.  Comments must be on thier own lines and begin with the pound sign (#).
# Blank lines are ignored.

# Command to enumerate directories
#Get-ChildItemd:\|?{$_.PSIsContainer}|Select-ObjectFullName

D:\OneDrive\Career
